[build]
  command = "npm run build"
  publish = ".next"
  base = "frontend"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PUBLIC_API_URL = "https://todo-list-production-7396.up.railway.app"
